/** Verbatim patient reviews from the original Tampa Bay Body Sculpting homepage scrape. */
export const patientTestimonials = [
  "Jeneé is an incredible advocate for my surgery, showcasing her expertise in cosmetic procedures, including body contouring techniques such as liposuction and the Brazilian butt lift. She has been holding my hand every step of the way, answering all of my questions, finding out what I need, and being very transparent about the process. I highly recommend her for anyone seeking natural-looking cosmetic surgery, whether it's a tummy tuck or male body contouring, in the Tampa Bay Body Sculpting community. 10/10 would recommend - Amber H.",
  "I could write an entire book about Tampa Bay Body Sculpting; they are incredibly sweet and patient. Their expertise in body contouring and cosmetic surgery, including procedures like Brazilian butt lifts and liposuction, is evident as they always check on you. They will call you back in a drop of a dime, showcasing their professionalism. I give them a 20/20, hands down, especially for their commitment to providing natural-looking cosmetic surgery, whether it's male body contouring or a tummy tuck.",
  "This was the best place I could've chosen for my liposuction and body contouring, thanks to their expertise in cosmetic surgery. I love the results; they look natural and fit perfectly, just like I hoped for with my tummy tuck. The staff was attentive and had great personalities that made me feel comfortable throughout the process. Thank you! - Grace J.",
  "The office is extremely responsive and will even reply late in the evening after business hours. With their expertise in cosmetic surgery, including body contouring procedures like Brazilian butt lift and liposuction, I\u2019m very pleased so far and can\u2019t wait to see my final results from Tampa Bay Body Sculpting - Courtney S. I'm also considering male body contouring options and a tummy tuck in the future.",
  "The communication from the first day I reached out to Tampa Bay Body Sculpting was unreal. Their expertise in body contouring and cosmetic surgery shone through as they answered all my questions (even after hours and on weekends). I felt so comfortable discussing options like the Brazilian butt lift, liposuction, and tummy tuck, and they went over the procedures thoroughly to ensure I was well-informed about my choice for natural-looking cosmetic surgery. - Amira P.",
  "Everyone there was quick to respond to communications, answering my questions about their expertise in cosmetic surgery, including procedures like body contouring, Brazilian butt lift, and liposuction. This responsiveness put my mind at ease regarding the natural-looking results I was considering, such as a tummy tuck or male body contouring. - Melissa M.",
] as const;
